Oloftrajs
linuxmao-org/Frontieres pull request #85
Opened 2019-08-21 11:54 UTC by olof29

ajout sauvegarde d'une trajectoire

2019-08-27 09:46 UTC, trebmuh requested changes

2019-08-27 09:46 UTC, trebmuh commented on translations/Frontieres_fr_FR.ts
> +        <translation>Extension (x)</translation>
"Extension X (x)" peut être ?

2019-08-27 09:46 UTC, trebmuh commented on translations/Frontieres_fr_FR.ts
> +        <translation>Applatissement</translation>
"Aplatissement".

Ceci dit, habituellement, "stretch" se traduit par "étirement". Si "aplatissement" est bien le mot à choisir, alors la version anglaise devrait être "flattening".

2019-08-27 09:46 UTC, trebmuh commented on translations/Frontieres_fr_FR.ts
> +        <translation>Enregistrée (&amp;R)</translation>
"`En&amp;registrée`"

2019-08-27 09:46 UTC, trebmuh commented on translations/Frontieres_fr_FR.ts
> +        <translation>Trajectoire (i)</translation>
"Trajectoire (I)"

2019-08-27 09:46 UTC, trebmuh commented on translations/Frontieres_fr_FR.ts
> +        <translation>Trajectoire: ENREGISTREE</translation>
ENREGISTRÉE

2019-08-27 09:46 UTC, trebmuh commented on translations/Frontieres_fr_FR.ts
> +        <translation>fixer le taux de rafraichissement en trames par seconde.</translation>
Paramétrer le taux de rafraîchissement en trames par seconde.
(set -> paramétrer, + majuscule, + accent circonflexe sur rafraîchissement)

2019-08-27 09:46 UTC, trebmuh commented on translations/Frontieres_fr_FR.ts
> +        <translation>taux de rafraichissement</translation>
+ accent circonflexe sur "rafraîchissement"

2019-08-27 09:46 UTC, trebmuh commented on translations/Frontieres_fr_FR.ts
> +        <translation>valeur de trames par seconde invalide.</translation>
manque une majuscule ici

2019-08-27 09:46 UTC, trebmuh commented on translations/Frontieres_fr_FR.ts
> +        <translation>Sauver la trajectoire</translation>
"Sauvegarder" est le terme habituellement utilisé, mais là, c'est "record", donc "Enregistrer" peut être ? Quelle est  la différence avec quelques lignes plus bas "Save trajectory" ?

2019-08-27 09:46 UTC, trebmuh commented on translations/Frontieres_fr_FR.ts
> +        <translation>Sauver la trajectoire</translation>
"Sauvegarder" est le terme habituellement utilisé

2019-08-27 10:15 UTC, olof29 commented
je regarde tout ça

2019-08-27 11:40 UTC, olof29 commented on translations/Frontieres_fr_FR.ts
> +        <translation>Sauver la trajectoire</translation>
Record est bien enregistrer : c'est la procédure qui permet d'enregistrer en mémoire la trajectoire qu'on va faire prendre manuelllement au cloud, tandis que save permet de sauvegarder sur le disque ce qui a été préalablement enregistré en mémoire

2019-08-27 14:42 UTC, olof29 commented
bon, j'ai eu un beau mic mac avec cette histoire de requete de changements, je me suis bien emmelé les pinceaux, et n'ai pas trouvé d'autre façon de m'y prendre pour demeler tout ça que de faire un pr sur mon fork et d'en repartir.
désolé pour le manque de clarté que ça donne dans la suite des pr, je n'ai pas su faire autrement.
mais ce pr englobe bien tous les commits que j'avais proposé avant, et les modifis demandées.

2019-08-27 15:11 UTC, trebmuh commented
Pas de lézard. Merci pour les changements.
Je laisse @jpcima valider le PR.

2019-08-30 07:14 UTC, olof29 commented
bon cette histoire de conflit, je ne la comprends pas vraiment, j'essaie de nettoyer des commentaires de debogage en vain, je pense qu'il faudra avoir passé ce pr avant de s'occuper de ça dans un prochain

2019-09-28 11:44 UTC, olof29 commented
bon, comme les pr ont posé souci a un moment, là je me trouve completement coincé, des modifs que je veux faire sont considérées comme des conflits maintenant. je ne peux pas résoudre ces conflits donc puisque ce sont des modifications à faire, je ne peux pas m'en passer.
comment fait on pour continuer ? ne serait il pas possible de passer ce pr, afin de pouvoir continuer a travailler ?

2019-09-28 12:15 UTC, jpcima commented
salut @olof29, j'ai résolu ce problème à l'instant :
J'ai fait un rebasage du travail de cette branche sur le master, et je l'ai fusionné manuellement.
Du coup tu peux donc continuer sur le master si ça t'est pratique.
(et cette PR est obsolète, mais je la laisse si tu veux traiter les quelques suggestions que @trebmuh 
a écrites)

2019-09-28 12:17 UTC, olof29 commented
merci.
je vais donc retravailler sereinement
les suggesstions de trebmuh sont deja prises en compte dans ce pr

2019-10-02 00:12 UTC, closed without merging